---
- hosts: main
  become: true  
  tasks:
    - name: Zip the NextCloud File
      command: "tar cvf /mnt/sdb1/nextcloud.backup.ansible.tar /mnt/sdb1/nextcloud"

- hosts: backup
  become: true
  tasks:
    - name: Transfer file from ServerA to ServerB
      command: "scp islab@{{ hostvars['main']['ansible_env'].SSH_CONNECTION.split(' ')[2] }}:/mnt/sdb1/nextcloud.backup.ansible.tar /mnt/sdb1/nextcloud.backup.ansible.tar"
