---
- hosts: Debian01
  tasks:
    - name: Debian git force reset
      command: git reset --hard origin/master
      args:
        chdir: /home/islab/Documents/SecretSharingIslab
        
    - name: Debian Update
      git:
        repo: git@github.com:hi8787h/SecretSharingIslab.git
        dest: /home/islab/Documents/SecretSharingIslab
        update: yes

- hosts: RasberryPi_4B_8G_01
  tasks:
    - name: RasberryPi 4B 8G 01 git force reset
      command: git reset --hard origin/master
      args:
        chdir: /home/islab/SecretSharingIslab
        
    - name: RasberryPi 4B 8G 01 Update
      git:
        repo: git@github.com:hi8787h/SecretSharingIslab.git
        dest: /home/islab/SecretSharingIslab
        update: yes

- hosts: RasberryPi_4B_8G_02
  tasks:
    - name: RasberryPi 4B 8G 02 git force reset
      command: git reset --hard origin/master
      args:
        chdir: /home/islab/SecretSharingIslab
        
    - name: RasberryPi 4B 8G 02 Update
      git:
        repo: git@github.com:hi8787h/SecretSharingIslab.git
        dest: /home/islab/SecretSharingIslab
        update: yes
