---
- hosts: Debian01
  tasks:
    - name: Get stuff from git
      git:
        repo: git@github.com:hi8787h/SecretSharingIslab.git
        dest: /home/islab/Documents/SecretSharingIslab
        update: yes

- hosts: RasberryPi_4B_8G_01
  tasks:
    - name: Get stuff from git
      git:
        repo: git@github.com:hi8787h/SecretSharingIslab.git
        dest: /home/islab/SecretSharingIslab
        update: yes

- hosts: RasberryPi_4B_8G_02
  tasks:
    - name: Get stuff from git
      git:
        repo: git@github.com:hi8787h/SecretSharingIslab.git
        dest: /home/islab/SecretSharingIslab
        update: yes